import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import TopNavigation from "./custom_components/header/TopNavigation";
import HeaderInfo from "./custom_components/header_info/HeaderInfo";
import "./globals.css";
import SubscribeSection from "./custom_components/subscribe/SubscribeSection";
import { AddressProvider } from "./(pages)/checkout/context/AddressContext";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Zestful Blends",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className + " w-full"}>
        <AddressProvider>
          <HeaderInfo />
          <TopNavigation />

            {children}
          <SubscribeSection />
        </AddressProvider>
      </body>
    </html>
  );
}


